### ISSUE TITLE
Unable to run mocha runner

### ISSUE THREAD

**Issue by tansaku** [snozza/sockerr#2]
```sh

→ node mocha_runner.js
express-session deprecated undefined resave option; provide resave option app.js:30:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:30:9
2015-01-29T16:01:44.979+0000 [initandlisten] connection accepted from 127.0.0.1:61596 #7 (1 connection now open)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
2015-01-29T16:01:44.987+0000 [conn7] end connection 127.0.0.1:61596 (0 connections now open)
````

**Comment by snozza** [comment]
Have updated Readme with further instructions.
Error: spawn ENOENT appears to be caused by invalid command - this suggests that mocha was not installed globally.

Please ensure mocha is installed, mongodb server daemon is running, and also the stand alone selenium server.

**Comment by tansaku** [comment]
thanks, done those.  I'm running mongodb and selenium server in the same window using the '&' unix utility.  Tests are now running, but I get these errors:

```sh

  1) Main page tests "before all" hook:
     RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

     Callstack:
     -> init()

  

  2) User "before all" hook:
     RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html

     Callstack:
     -> init()

```

**Comment by snozza** [comment]
Readme has been updated to include instructions for download the chromedriver and placing it on your system path:

Setup:

```
Ensure that mocha is installed globally:

$ npm install mocha -g

Download the chromedriver executable from http://chromedriver.storage.googleapis.com/index.html and place it on your path (e.g. /usr/local/bin).
Futher information can be found at https://code.google.com/p/selenium/wiki/ChromeDriver

Download the Selenium stand-alone server from http://http://www.seleniumhq.org/download
then in a separate terminal run:

$ java -jar /pathtofile/selenium-server-standalone-2.44.0.jar

Ensure that MongoDB is installed and run a mongodb server daemon in a seperate terminal

$ mongod
```

Let me know if this fixes the setup issue for you.

**Comment by tansaku** [comment]
yep that fixed it, thanks! :-)

BTW, do you have some sort of database cleaner operation going on here to tidy up after the test runs?

**Comment by snozza** [comment]
I just pushed the little module that I made, it can be found in the helpers file (dbCleaner).
It erases the db between each test (note that this was slightly faster than dropping collections one by one).

The mocha_runner app also drops/disconnects the test database at the end up the test suite run.
